project/models.py
# project/models.py


import datetime

from project import db, bcrypt


class User(db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String(255), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    registered_on = db.Column(db.DateTime, nullable=False)
    admin = db.Column(db.Boolean, nullable=False, default=False)
    scorecards = db.relationship("ScoreCard", backref="user")


    def __init__(self, email, password, admin=False):
        self.email = email
        self.password = bcrypt.generate_password_hash(password)
        self.registered_on = datetime.datetime.now()
        self.admin = admin

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id

    def __repr__(self):
        return '<User {0}>'.format(self.email)



class Hole(db.Model):
    """ June 7th: not going to use this for now"""
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    hole_number = db.Column(db.Integer, nullable=False)
    par = db.Column(db.Integer, nullable=False)


class Score(db.Model):
    """ every time a player plays a hole, add one of these
    June 7th: will do basic ScoreCard for now.
    """
    __tablename__ = "scores"
    # Number of Strokes
    # Amount Over or Under Par

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    num_strokes = db.Column(db.Integer)

class ScoreCard(db.Model):
    """ A collection of Score's """
    def as_dict(self):
        return {c.name: getattr(self, c.name) for c in self.__table__.columns}

    __tablename__ = "scorecards"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    # saving scores just as a string for now
    # ex. 1-3,2-4,3-9
    # Hole 1: 3 strokes, Hole 2: 4 strokes, Hole 3: 9 strokes. etc.
    scores = db.Column(db.String(255))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))



"""
ScoreCard-
id
User (in future can add other User's to the card)
Date (when it was created)
Course Name (String - in future can be a selection of all real courses or whatever)
Location (not mandatory)


"""

project/user/forms.py
# project/user/forms.py

from flask_wtf import Form
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email, Length, EqualTo

class LoginForm(Form):
    email = StringField('Email Address', [DataRequired(), Email()])
    password = PasswordField('Password', [DataRequired()])

class RegisterForm(Form):
    email = StringField(
        'Email Address',
        validators=[DataRequired(), Email(message=None), Length(min=6, max=40)])
    password = PasswordField(
        'Password',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        'Confirm password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match.')
        ]
    )

project/__init__.py
# project/__init__.py


#################
#### imports ####
#################

import os

from flask import Flask, render_template
from flask.ext.login import LoginManager
from flask.ext.bcrypt import Bcrypt
from flask.ext.debugtoolbar import DebugToolbarExtension
from flask_bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy


################
#### config ####
################

app = Flask(__name__)
app.config.from_object(os.environ['APP_SETTINGS'])


####################
#### extensions ####
####################

login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
toolbar = DebugToolbarExtension(app)
bootstrap = Bootstrap(app)
db = SQLAlchemy(app)


###################
### blueprints ####
###################

from project.user.views import user_blueprint
from project.main.views import main_blueprint
from project.api.views import api_blueprint
from project.scorecard.views import scorecard_blueprint

app.register_blueprint(user_blueprint)
app.register_blueprint(main_blueprint)
app.register_blueprint(api_blueprint)
app.register_blueprint(scorecard_blueprint)

###################
### flask-login ####
###################

from project.models import User

login_manager.login_view = "user.login"
login_manager.login_message_category = 'danger'


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


########################
#### error handlers ####
########################

@app.errorhandler(403)
def forbidden_page(error):
    return render_template("errors/403.html"), 403


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

project/api/views.py
# project/api/views.py


#################
#### imports ####
#################

from flask import Blueprint, request, session, g
from flask_restful import Api, Resource, url_for, reqparse, abort, fields, marshal

from flask.ext.login import login_required, current_user
from sqlalchemy.exc import IntegrityError

from project import bcrypt, db
from project.models import User, ScoreCard

from flask_wtf import Form
from wtforms import StringField, IntegerField
from wtforms.validators import DataRequired, Email, Length, EqualTo



################
#### config ####
################

api_blueprint = Blueprint('api', __name__,)
api = Api(api_blueprint)


####
# Forms Validation
####

# June 7th: not sure if best way to validate data is with forms.
class ScoreCardForm(Form):
    decorators = []
    scores = StringField(
        'Scores',
        validators=[DataRequired(), Length(min=6, max=25)])

################
### resources ##
################

""" ScoreCard API
HTTP: URI
    - ACTION
GET : http://[hostname]/api/scorecards/[user_id]
    - Retrieves list of all user's scorecards

GET : http://[hostname]/api/scorecards/[user_id]/[scorecard_id]
    - Retrieves a ScoreCard

POST: http://[hostname]/api/scorecards/[user_id]
    - Create a new ScoreCard

PUT : http://[hostname]/api/scorecards/[user_id]/[scorecard_id]
    - Update an existing ScoreCard

DELETE: http://[hostname]/api/scorecards/[user_id]/[scorecard_id]
    - Delete a ScoreCard

*** Data Fields ***
URI: unique URI for ScoreCard. <String>
Date: DateTime Played. <String>


To Be Added:
Course: Name of Course. <String>
Users: ID of other users on this scorecard. (Not sure what type)

"""

scorecard_fields = {
   'scores': fields.String,
   'user_id': fields.Integer,
   'uri': fields.Url('scorecard')
}




class ScoreCardListAPI(Resource):
    decorators = [login_required]

    def __init__(self):
        self.reqparse = reqparse.RequestParser()
        # self.reqparse.add_argument()

    def get(self):
        # get all scorecards
        user_id = current_user.id

        # query database of User with id of user_id
        user = User.query.filter_by(id=user_id).first()
        # user.scorecards is list of all a User's scorecards
        # as_dict() is method on Scorecard model turns model
        # into something JSON serializable.
        results = [card.as_dict() for card in user.scorecards]

        return {'scorecards': results} # return json

    def post(self):
        # create new ScoreCard
        form = request.form

        # TODO: Add parser, depending on score format we settle on.
        parser = reqparse.RequestParser()
        parser.add_argument('scores', type=str, required=True, help='golf scores in string format')
        parser.add_argument('user_id', type=int, required=True, help='scorecard owner user id')

        args = parser.parse_args()

        user_id = current_user.id
        # new_scorecard = ScoreCard(
        #     scores=form['scores'],
        #     user_id=user_id
        # )

        new_scorecard = ScoreCard()
        new_scorecard.scores = args["scores"]
        new_scorecard.user_id = args["user_id"]

        try:
            db.session.add(new_scorecard)
            db.session.commit()
            print(new_scorecard.as_dict())
            return new_scorecard.as_dict(), 201

        except IntegrityError, exc:
            return {"error": exc.message}, 500

        # return success
        # return {'scorecard': marshal(new_scorecard, scorecard_fields)}, 201


class ScoreCardAPI(Resource):
    decorators = [login_required]

    def get(self, card_id):
        user_id = current_user.id
        return {'example': str(user_id) + ' ' + str(card_id)}

    def put(self, card_id):
        pass

    def delete(self, card_id):
        pass



api.add_resource(ScoreCardListAPI, '/api/scorecards', endpoint="scorecard_list")
api.add_resource(ScoreCardAPI, '/api/scorecards/<int:card_id>', endpoint="scorecard")

project/main/__init__.py
# project/public/__init__.py

project/main/views.py
# project/main/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint


################
#### config ####
################

main_blueprint = Blueprint('main', __name__,)


################
#### routes ####
################


@main_blueprint.route('/')
def home():
    return render_template('main/home.html')


@main_blueprint.route("/about/")
def about():
    return render_template("main/about.html")

project/scorecard/__init__.py
# project/scorecard/__init__.py

project/scorecard/views.py
# project/scorecard/views.py


from flask import render_template, Blueprint


#################
#### imports ####
#################

from flask import render_template, Blueprint

from flask.ext.login import login_required

from project import bcrypt, db
from project.models import User
from project.user.forms import LoginForm, RegisterForm

################
#### config ####
################

scorecard_blueprint = Blueprint('scorecard', __name__,)


################
#### routes ####
################


@scorecard_blueprint.route('/scorecards/all')
@login_required
def scorecard_main():
    return render_template('scorecard/scorecards.html')

project/user/__init__.py
# project/user/__init__.py

project/user/views.py
# project/user/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask.ext.login import login_user, logout_user, login_required, \
    LoginManager, current_user

from project import bcrypt, db
from project.models import User
from project.user.forms import LoginForm, RegisterForm

################
#### config ####
################

user_blueprint = Blueprint('user', __name__,)
login_manager = LoginManager()

@login_manager.user_loader
def user_loader(user_id):
    """  Given *user_id*, return the associated User object.
    :param unicode user_id: user_id (email) user to retrieve
    """
    return User.query.get(user_id)




################
#### routes ####
################

@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            password=form.password.data
        )
        db.session.add(user)
        db.session.commit()

        login_user(user)

        flash('Thank you for registering.', 'success')
        return redirect(url_for("user.members"))

    return render_template('user/register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('You are logged in. Welcome!', 'success')
            return redirect(url_for('user.members'))
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', title='Please Login', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out. Bye!', 'success')
    return redirect(url_for('main.home'))


@user_blueprint.route('/members')
@login_required
def members():
    return render_template('user/members.html')

project/templates/_base.html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <title>GolfMeet Beta{% block title %}{% endblock %}</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
{#    <link href="{{url_for('static', filename='main.css')}}" rel="stylesheet" media="screen">#}
    <link href="{{  url_for('static', filename='stylesheets/bootstrap.css')}}" type="text/css" media="screen" rel="stylesheet">
    <link href="{{ url_for('static', filename='stylesheets/global.css')}}" type="text/css" media="screen" rel="stylesheet">

    <!-- fonts -->
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100,700' rel='stylesheet' type='text/css'>


    {% block css %}{% endblock %}
  </head>

  <body>

    {% include 'header.html' %}

    <div class="site-content">
      <div class="container">

        <!-- messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <br>
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
             {{message}}
            </div>
            {% endfor %}
          </div>
        </div>
        {% endif %}
        {% endwith %}


        <!-- child template -->
        {% block content %}{% endblock %}

        <br>

        <!-- errors -->
        {% if error %}
          <p class="error"><strong>Error:</strong> {{ error }}</p>
        {% endif %}

      </div>
    </div>

    <br><br>

    {% include 'footer.html' %}

    <!-- scripts -->
    <script src="//code.jquery.com/jquery-1.11.2.min.js" type="text/javascript"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="{{url_for('static', filename='js/build/main.js')}}" type="text/javascript"></script>
    {% block js %}{% endblock %}

  </body>
</html>

project/templates/footer.html
<footer>
  <div class="container">
    <small>
      <span>©2015 Golf Meet</a></span>
    </small>
  </div>
</footer>

project/templates/header.html
     <nav class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
          <a class="navbar-brand" href="{{ url_for('main.home') }}">
            <img src="{{ url_for('static', filename='images/Golfmeet-logo5.png')}}" height="45px">
          </a>
            <ul class="nav navbar-nav">
          <li><a href="{{ url_for('main.about') }}">About</a></li>
          {% if current_user.is_authenticated() %}
           <li><a href="{{ url_for('user.members') }}">Dashboard</a></li>
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated() %}
            <li><a href="{{ url_for('user.logout') }}" class="btn btn-default navbar-btn navbar-right">Logout</a></li>
          {% else %}
            <li><a href="{{ url_for('user.login') }}" class="btn btn-default navbar-btn navbar-right signUpButton"><span class="glyphicon glyphicon-user"></span>&nbsp;Register/Login</a></li>
          {% endif %}
        </ul>
        </div>
      </nav>

      <!-- __________________________________________________________________________________________ -->

{##}
{##}
{##}
{#<header class="site-header">#}
{##}
{##}
{##}
{#  <!-- Navigation -->#}
{#  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">#}
{#    <div class="container">#}
{#      <!-- Brand and toggle get grouped for better mobile display -->#}
{#      <div class="navbar-header">#}
{#        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">#}
{#          <span class="sr-only">Toggle navigation</span>#}
{#          <span class="icon-bar"></span>#}
{#          <span class="icon-bar"></span>#}
{#          <span class="icon-bar"></span>#}
{#        </button>#}
{#          <a class="navbar-brand" href="{{ url_for('main.home') }}">GolfMeet Beta</a>#}
{#      </div>#}
{#      <!-- Collect the nav links, forms, and other content for toggling -->#}
{#      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">#}
{#        <ul class="nav navbar-nav">#}
{#          <li><a href="{{ url_for('main.about') }}">About</a></li>#}
{#          {% if current_user.is_authenticated() %}#}
{#           <li><a href="{{ url_for('user.members') }}">Dashboard</a></li>#}
{#          {% endif %}#}
{#        </ul>#}
{#        <ul class="nav navbar-nav navbar-right">#}
{#          {% if current_user.is_authenticated() %}#}
{#            <li><a href="{{ url_for('user.logout') }}">Logout</a></li>#}
{#          {% else %}#}
{#            <li><a href="{{ url_for('user.login') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;Register/Login</a></li>#}
{#          {% endif %}#}
{#        </ul>#}
{#      </div>#}
{#      <!-- /.navbar-collapse -->#}
{#    </div>#}
{#    <!-- /.container -->#}
{#  </nav>#}
{#</header>#}